# Generated by Django 5.2.1 on 2025-06-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('age', models.PositiveIntegerField(verbose_name='Patient Age')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Additional Instructions')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/', verbose_name="Doctor's Voice Note")),
                ('doctor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Doctor Signature')),
                ('doctor_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Clinic Logo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/', verbose_name='Prescription PDF')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='Date Issued')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('appointment', models.ForeignKey(help_text='Related appointment from which patient info is derived', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor who issued this prescription', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Medication Name')),
                ('dosage', models.CharField(max_length=255, verbose_name='Dosage')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescription.prescription')),
            ],
        ),
    ]
