# Generated by Django 5.2.4 on 2025-10-10 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctor', '0001_initial'),
        ('prescription', '0002_prescription_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='Example: 500 mg — 1 tab PO q8h × 5 days', max_length=255, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Patient’s age at time of prescribing (auto-calculated if not provided).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Patient Age'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor who issued this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Clinic Logo'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Doctor Signature'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_full_name',
            field=models.CharField(help_text="Snapshot of patient's name at time of prescribing", max_length=100, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Prescription PDF'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'm4a'])], verbose_name="Doctor's Voice Note"),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_c6f9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'date_issued'], name='prescriptio_doctor__ce493e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['appointment'], name='prescriptio_appoint_2c10b0_idx'),
        ),
    ]
