# Generated by Django 5.2.1 on 2025-06-26 18:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import medical_archive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Visit Note 1, Blood Test Result', max_length=255)),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes or case description")),
                ('archive_type', models.CharField(choices=[('visit', 'Visit'), ('lab', 'Lab Result'), ('scan', 'Scan'), ('prescription', 'Prescription'), ('other', 'Other')], default='visit', help_text='Type of archive: Visit, Lab Result, Scan, etc.', max_length=50)),
                ('is_critical', models.BooleanField(default=False, help_text='Check if the archive contains critical or urgent information')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_by', models.ForeignKey(help_text='User who created this archive entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor who created this archive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_patient_archives', to='doctor.doctor')),
                ('patient', models.ForeignKey(help_text='Select the patient for this archive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Patient Archive',
                'verbose_name_plural': 'Patient Archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload PDF, image, or document related to the archive', upload_to=medical_archive.models.archive_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif']), medical_archive.models.validate_file_size])),
                ('description', models.CharField(blank=True, help_text='e.g., Blood Test PDF, Chest Scan Image', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('archive', models.ForeignKey(help_text='Parent archive this file is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_archive.patientarchive')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
