# Generated by Django 5.2.1 on 2025-06-17 14:47

import django.db.models.deletion
import patient.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[patient.models.validate_mobile], verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('past_medical_history', models.TextField(blank=True, null=True, verbose_name='Past Medical History')),
                ('drug_history', models.TextField(blank=True, null=True, verbose_name='Drug History')),
                ('investigations', models.TextField(blank=True, null=True, verbose_name='Investigations')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('hbA1c_level', models.FloatField(blank=True, null=True, verbose_name='HbA1c Level')),
                ('blood_glucose_level', models.FloatField(blank=True, null=True, verbose_name='Blood Glucose Level')),
                ('hypertension', models.BooleanField(default=False, verbose_name='Has Hypertension?')),
                ('heart_disease', models.BooleanField(default=False, verbose_name='Has Heart Disease?')),
                ('smoking_history', models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current'), ('not available', 'Not Available'), ('No Info', 'No Info')], max_length=50, null=True, verbose_name='Smoking History')),
                ('race', models.CharField(blank=True, choices=[('AfricanAmerican', 'African American'), ('Asian', 'Asian'), ('Caucasian', 'Caucasian'), ('Hispanic', 'Hispanic'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Race')),
                ('diabetes_prediction', models.CharField(blank=True, help_text='Auto-generated by AI model', max_length=50, null=True, verbose_name='Diabetes Prediction')),
                ('clinical_notes', models.TextField(blank=True, help_text='Generated or added by doctor', null=True, verbose_name='Clinical Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_patients', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['full_name'],
            },
        ),
    ]
