# Generated by Django 5.2.1 on 2025-06-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, help_text='Date and time of the appointment', null=True, verbose_name='Scheduled Time')),
                ('queue_number', models.PositiveIntegerField(blank=True, help_text="Auto-generated based on the doctor's daily appointments", null=True, verbose_name='Queue Number')),
                ('iqd_amount', models.DecimalField(decimal_places=0, default=0, help_text='Amount in Iraqi dinars', max_digits=15, verbose_name='Amount (IQD)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the appointment', null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the appointment', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('doctor', models.ForeignKey(help_text='Doctor who will see the patient', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(help_text='Select the patient from the registered list', on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_time'], name='appt_doctor_sched_idx'), models.Index(fields=['scheduled_time'], name='appt_sched_idx'), models.Index(fields=['created_at'], name='appt_created_idx')],
            },
        ),
    ]
