# Generated by Django 5.2.1 on 2025-06-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Contact Information')),
                ('scheduled_time', models.DateTimeField(verbose_name='Requested Time')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('doctor', models.ForeignKey(help_text='Doctor the patient wants to consult', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Requested Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('related_booking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.patientbookingrequest', verbose_name='Related Booking Request')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, help_text='Date and time of the appointment', null=True, verbose_name='Scheduled Time')),
                ('queue_number', models.PositiveIntegerField(blank=True, help_text="Auto-generated based on the doctor's daily appointments", null=True, verbose_name='Queue Number')),
                ('iqd_amount', models.DecimalField(decimal_places=0, default=0, help_text='Amount in Iraqi dinars', max_digits=15, verbose_name='Amount (IQD)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the appointment', null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the appointment', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('doctor', models.ForeignKey(help_text='Doctor who will see the patient', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(help_text='Select the patient from the registered list', on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_time'], name='appt_doctor_sched_idx'), models.Index(fields=['scheduled_time'], name='appt_sched_idx'), models.Index(fields=['created_at'], name='appt_created_idx')],
            },
        ),
    ]
