# Generated by Django 5.2.1 on 2025-06-26 18:21

import django.db.models.deletion
import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[doctor.models.validate_phone], verbose_name='Phone Number')),
                ('clinic_address', models.TextField(blank=True, verbose_name='Clinic Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Profile Photo')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('short_bio', models.CharField(blank=True, help_text="A brief summary displayed on the doctor's profile card.", max_length=255, verbose_name='Short Biography')),
                ('available', models.BooleanField(default=True, help_text='Indicates whether this doctor is publicly available for appointments.', verbose_name='Available for Booking')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average patient rating.', max_digits=3, verbose_name='Rating')),
                ('consultation_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consultation Fee (IQD)')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Number of years the doctor has practiced medicine.', null=True, verbose_name='Years of Experience')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'indexes': [models.Index(fields=['specialty'], name='doctor_doct_special_b9e018_idx')],
            },
        ),
    ]
