# Generated by Django 5.2.1 on 2025-06-17 14:47

import django.db.models.deletion
import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[doctor.models.validate_phone], verbose_name='Phone Number')),
                ('clinic_address', models.TextField(blank=True, verbose_name='Clinic Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'indexes': [models.Index(fields=['specialty'], name='doctor_doct_special_b9e018_idx')],
            },
        ),
    ]
